version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api/Dockerfile
  sqldata:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Passw*rd1"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433